### ISSUE TITLE
Performance Issue: App Object Approver needs 2 min to display 3318 sheets

### ISSUE THREAD

**Issue by PrzemyslawMarcinczak** [eapowertools/QlikSenseQMCUtility#111]
Hi,

Performance Issue: App Object Approver needs 2 min to display 3318 sheets on super fast machine:

CPU- 48
RAM - 512 GB
Qlik Sense 3.2.4

Best Regards
Przemyslaw Marcinczak

**Comment by jparis** [comment]
Will be phasing out this plugin as this functionality has made it into the June 2018 Qlik Sense release.
