### ISSUE TITLE
EA Power Tools Service Dispatcher Prevents QS Service Dispatcher from Starting

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/QlikSenseQMCUtility#18]
One will start but the other will not; works both ways. Looks like the issue is port contention.

**Comment by goldbergjeffrey** [comment]
Please read the note **[here](https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Critical-Issue-with-QMC-Utilities-1.0.0.0-Requires-Immediate-Attention)**.  Unfortunately, the service dispatcher we created to handle QMC Utilities conflicts with Qlik Sense Service dispatcher.
