### ISSUE TITLE
The link to the install doc does not appear to be working

### ISSUE THREAD

**Issue by lyonsdave** [eapowertools/QlikSenseQMCUtility#24]

**Comment by alexometis** [comment]
Yes, "https://linktoinstalldocument/" doesn't work - I'm not sure if this is because the install doc doesn't exist yet or the link is broken...

**Comment by goldbergjeffrey** [comment]
Install Document link fixed and working!  **[https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities](https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities)**
