### ISSUE TITLE
Rule Manager- Wont import rules

### ISSUE THREAD

**Issue by mody7860** [eapowertools/QlikSenseQMCUtility#27]
I tried to use the Rule Manager.  I can successfully export the rules from System1.  I then try to import the rules from the json file into System2.   The rule manager returns an error.  This is regardless of whether i try importing one/multiple rules.  

Error from the import status column - 
Failed.  Received error code: 400:: The&quot;Add&quot; operation failed.  

Thoughts?

**Comment by goldbergjeffrey** [comment]
@mody7860, will perform a test and have a look.
You have QMC Utilities installed on two separate systems?

**Comment by mody7860** [comment]
Thanks. Correct I have installed the Utils on two separate systems.

**Comment by goldbergjeffrey** [comment]
@mody7860 I tested exporting and importing rules and the capability appears to be working correctly.   so I'm suspecting that there is a configuration issue with system 2.  You may want to try exporting a rule from system 2 and importing on 1 and seeing if import works on one.

If possible, please send me installconfig.js files from boths systems and I'll have a look.

**Comment by mody7860** [comment]
The installconfig.js files attached.  For security reasons - I have changed
the server names but kept the naming convention consistent with domain etc.


Also, I tried to import export 1 rule between server 1 and server 2 and
vice versa and no luck.

Question - what happens if the rule exists in the target system.  Does it
get added as a new rule with a seperate id or is the existing rule
modified?

**Comment by goldbergjeffrey** [comment]
Looks like the js files got stripped for some reason.

**Comment by mody7860** [comment]
attaching zip files.  Let me know if you receive them.

**Comment by goldbergjeffrey** [comment]
I think you have to come to the github issues page instead of responding to the emails to add the attachments.

**Comment by mody7860** [comment]
So the zip file didnt come thru either?  If so send me the GIT issues link
to upload the zip.

**Comment by goldbergjeffrey** [comment]
the issues thread is at the bottom of the email where it says **Reply to this email directly, view it on GitHub** and then the comment number.

**Comment by mody7860** [comment]
Attached!!

[Importing_SYSTEM_installConfig.zip](https://github.com/eapowertools/QlikSenseQMCUtility/files/564887/Importing_SYSTEM_installConfig.zip)

**Comment by goldbergjeffrey** [comment]
for the hostname, did you enter that manually or overwrite what the installer found?

**Comment by mody7860** [comment]
Overwrote it with the same level notation and removed the original server
and domain names for purposes of sharing outside the org.

**Comment by goldbergjeffrey** [comment]
I mean when you performed the install.  Was it fqdn then?  Are you using 3rd party cert?  central nodes or rim nodes (may have asked this already)?

**Comment by mody7860** [comment]
The files were left untouched from the original install.  No 3rd party
cert.  Out of the box qlik install on a single server which also serves at
the central node.

**Comment by goldbergjeffrey** [comment]
Moving issue to proper repo: **https://github.com/eapowertools/qmcu-rule-manager/issues/3**
