### ISSUE TITLE
Unable to use link the the install guide.

### ISSUE THREAD

**Issue by dwayler** [eapowertools/QlikSenseQMCUtility#28]
Also tried the install on my Rim box.  Unable to browse to http://localhost:9945.  Wanting to try to troubleshoot with the install guide or if you have any ideas for me to try.

**Comment by alexometis** [comment]
The link is http**s**://localhost:9945/ - note the **s** in http**s**. Caught me out first time too!

**Comment by goldbergjeffrey** [comment]
sorry folks.  I'll fix the install guide.  We are going https only from now on.

**Comment by goldbergjeffrey** [comment]
Install Document link fixed and working!  **[https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities](https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities)**
