### ISSUE TITLE
Feature Request - Authorisation

### ISSUE THREAD

**Issue by alexometis** [eapowertools/QlikSenseQMCUtility#29]
As far as I can tell, there's no authorisation built into the tools, unless I'm missing something. Installing this on a Production system is unlikely therefore. You could firewall the port and only allow login from the server or approved IPs of course, but it would be great it it hooked in to the QS roles or at least had a simple username & password protection...

**Comment by alexometis** [comment]
> authentication

I meant authorisation really didn't I :)

**Comment by sc305495** [comment]
I agree, this is basically essential for a production implementation, would love to see this!

**Comment by goldbergjeffrey** [comment]
On the roadmap for January.  I've tested it and it works.  But we are wrapping up some additional tools before we implement this capability.

**Comment by goldbergjeffrey** [comment]
Implemented in 3.0.3: **https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/3.0.3**
