### ISSUE TITLE
QMC Utilities Tool Installation Error

### ISSUE THREAD

**Issue by ssunkanmis** [eapowertools/QlikSenseQMCUtility#33]
I’m having some issues with the installation and link for installation guide is not working.  Copied the files from QMC Utilities config folder and paste it in the ServiceDispatcher folder and still not working. 

**Error Message:
![qmc utilities error message](https://cloud.githubusercontent.com/assets/23389716/20196800/f47d4f48-a761-11e6-97c9-725e88c16c90.jpg)
** Runtime Error (at 69:296):
Cannot open file D:\Program Files\\ServiceDispatcher\services.conf
Qlik Sense Service Dispatcher

Thank you.

![Uploading QMC Utilities error message.jpg…]()

**Comment by goldbergjeffrey** [comment]
sorry I'm just seeing this now.  Looks like it can't find your Qlik Sense installation directory.  Have you removed and attempted to reinstall QMC Utils?

**Comment by goldbergjeffrey** [comment]
We just updated to 2.0.  You may want to try that install and see if you continue to experience a problem.  I haven't received an answer to my question so I'm closing this issue.  Please reopen and comment if this continues to be a problem.
