### ISSUE TITLE
Qlik EA Power Tools service dispatcher service doesn't start

### ISSUE THREAD

**Issue by mhr2015** [eapowertools/QlikSenseQMCUtility#40]
Hi Jeff,

after installation, the service doesn't start or rather, isn't even visible in the service manager. the website @<server_name>:9945 isn't reachable therefore.

We tried it on two different Win 10 laptops, Sense server 3.1.3 and 3.1.2.

Thank you, best regards,
Matthias

**Comment by goldbergjeffrey** [comment]
Interesting...  So you are trying to run on desktop OS?  So I've seen some issues with Windows 7, but not Windows 10.  If you check Services does the Qlik EA Powertools Service Dispatcher show up in the list?  If not, then the script that runs during install did not work.

Question, when you ran install, did you run with elevated privs?

**Comment by goldbergjeffrey** [comment]
@mhr2015 I just tested windows 10 install and run of QMC Utilities and it came up.  Did you try https?

**Comment by mhr2015** [comment]
Hi Jeff, I tried https of course, but the "Qlik EA Powertools Service Dispatcher" does NOT show up as a windows service. I re-ran the installer (https://s3.amazonaws.com/eapowertools/qmcutilities/QMCUtilities.exe ) with Admin privileges, but to no avail. Any ideas? Thank you!

**Comment by mhr2015** [comment]
I uninstalled and installed v2.0 again with admin privileges and it's working now! Thank you :-)

**Comment by goldbergjeffrey** [comment]
ok, good to read.  SC.exe (the exe that adds services) can be a bit finicky on desktop OS.
