### ISSUE TITLE
App Mover doesn't work

### ISSUE THREAD

**Issue by mhr2015** [eapowertools/QlikSenseQMCUtility#41]
Trying to move one or several apps between two servers (1 in the cloud) did not work, I tried both directions. Reading the apps from the respective source servers works (so certificates are set up correctly within the cert sub-folder), but the "Deploy" button seems to have no effect. No error message or any kind of feedback apears.

**Comment by jparis** [comment]
Closing issue here and moving issue to qpp-mover repository. Link: https://github.com/eapowertools/qmcu-app-mover/issues/11
