### ISSUE TITLE
Sheet Approver doesn't update

### ISSUE THREAD

**Issue by SandroK** [eapowertools/QlikSenseQMCUtility#44]
We have an issue with the sheet approver in the QMC utilities. The data is stuck in a state from some time yesterday afternoon. Until then we can't recall any issues. Yesterday afternoons data must have gotten in there somehow as well, after all.
 
I imported an app yesterday and have since published it several times under various names into various streams. But the sheet approver still claims (and has done so all the time inbetween) that the app is stuck in the "work" area.

To clarify: in this particular case the app is published with all its sheets, but in the Sheet Approver it still shows with "Not approved" and "Not published".
 
What have we already tried?
- reloading the page (obviously) :-)
- restarting all the services (any Service that starts with Qlik)
- removing the QMC Utilities (Uninstall.exe, sc delete QlikEAPowerToolsServiceDispatcher, remove "C:\Program Files\Qlik\Sense\EAPowerTools" path manually, restart server (the entire machine)) and reinstalling (both 2.0.0 and 2.0.1)
 
What else can I contribute?
- the repository shows correct information (we have an app, which directly accesses the Repository DB)
- the same data from yesterday afternoon was displayed again even after re-installation
- the certificates are available at "C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates"

P.S. A few app imports and days later (that's when I checked again) the information was indeed updated. So I have repeated the process with a different app now and we have the same issue. Publish app, see the app in the new stream, check Sheet Approver and be told that it is still in the work area.

**Comment by goldbergjeffrey** [comment]
@SandroK, can you send some screenshots?  what version of Qlik Sense?

**Comment by SandroK** [comment]
The browser cache seems to have been the problem. Turning it off (by requesting new items on every website visit) has solved the issue. I'll leave this open, as maybe there is room for improvement to avoid this kind of problem in the future. If you still need screenshots, let me know. It's Qlik Sense 3.0.4

**Comment by goldbergjeffrey** [comment]
I'm surprised this was an issue, but we will look into it.

**Comment by goldbergjeffrey** [comment]
@SandroK, I've updated sheet approver to be app object approver.  Please try it and see if it resolves the updating problem.  I was not able to recreate this issue.

**[2.02 Installer](https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2)**
