### ISSUE TITLE
Cannot start after installation -- "localhost refused to connect"

### ISSUE THREAD

**Issue by PlexPro** [eapowertools/QlikSenseQMCUtility#45]
Hi,

Yesterday I installed this on my Qlik Sense Enterprise Server.  Everything appeared to install normally, and when I was prompted for Qlik service user profile credentials, I supplied the AD account used by the Qlik Sense services; it is also the default admin account for the Qlik install.

However, when I tried to go to "https://localhost:9945" (localhost worked for GMS), I got

This site can’t be reached
localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I also tried the full server name "https://vm-win-analytics.polywoodinc.local:9945", to no avail.

This morning I uninstalled and reinstalled it.  I noted that it did not uninstall the service dispatcher service, as rather than prompting me for credentials, it advised that it was stopping the service, and then restarted it.

Did I use the wrong credentials?  If so, how would I respecify them?  I can find no way to uninstall the dispatcher.

I don't know whether this be relevant, but I noted that in "PowerToolsServiceDispatcher\services.conf" is this line under the "[QMCUtilities]" section:

ExePath=..\..\ServiceDispatcher\Node\node.exe

No such path exists... is that significant?

**Comment by goldbergjeffrey** [comment]
Did you install using Admin Privs?  And What OS?  We have seen sporadic issues with the installation of the powertools service dispatcher.  Check to see if the Qlik EAPowertools Service Dispatcher was created in Services.
and yes the EXEpath is correct because it's supposed to point to %QlikSenseInstall%\ServiceDispatcher\Node\Node.exe.  For example, if you installed Qlik Sense in defaults then node.exe is located at C:\Program Files\Qlik\Sense\ServiceDispatcher\Node\Node.exe

You will want to install EAPowertools in the same install location as Qlik Sense.  For Example you resulting dir structure would be c:\program files\qlik\sense\eapowertools.

When you installed did you add certificates for friendly hostname?  If not, when you tried localhost did you try it from the server or from your local?  Keep in mind as well QMC Utilities needs to be installed on  a server running Qlik Sense server.

**Comment by PlexPro** [comment]
Hello Jeff,

> Did you install using Admin Privs?

Yes, I was logged in with a domain user profile which is part of the Administrators group.

> What OS?

Windows (Server) 2012 R2

> Check to see if the Qlik EAPowertools Service Dispatcher was created in Services.

No, it was not.  That was one reason I uninstalled QMCUtility, hoping that it might permit reinstallation of the EAPowertools Service Dispatcher, since I found no independent way to uninstall it.

> ...if you installed Qlik Sense in defaults then node.exe is located at C:\Program Files\Qlik\Sense\ServiceDispatcher\Node\Node.exe

Ah, okay, I found it.

> You will want to install EAPowertools in the same install location as Qlik Sense.

Yes, I did that; took the default location, same as GMS.  I have verified that every time I've been spelunking in the Qlik Sense installation.

> When you installed did you add certificates for friendly hostname?  If not, when you tried localhost did you try it from the server or from your local?  Keep in mind as well QMC Utilities needs to be installed on a server running Qlik Sense server.

No, I did not add a certificate (would that permit use from a remote browser?).  It's co-installed with Qlik Sense Server, and I am attempting access from the server.

Thanks,

René

**Comment by goldbergjeffrey** [comment]
Powertools service dispatcher install is firing inconsistently.  Take this code and put into a batch file.  Specify the path to the service dispatcher file, the userid, and password that will run the service.

```
sc query "QlikEAPowerToolsServiceDispatcher"

IF %ERRORLEVEL% EQU 0 (GOTO END) ELSE (GOTO ADDSERVICE)

:ADDSERVICE
sc create QlikEAPowerToolsServiceDispatcher binPath= "%~1\PowerToolsServiceDispatcher\PowerToolsService.exe" DisplayName= "Qlik EAPowerTools Service Dispatcher" start= auto obj= %2 password= %3
sc description "QlikEAPowerToolsServiceDispatcher" "Service Dispatcher for running EA Powertools" 

:END
```

**Comment by PlexPro** [comment]
Hi Jeff,

Executing this hasn't worked for us:

C:\Users\Public\Documents\Qlik\FixQlikEAPowerToolsServiceDispatcher.bat "qliksensesvc" "password"

When we actually put the credentials in the script, it did then successfully install.  Once the service started, however, we still could not connect, the result was the same...

I am logged in Windows as a user profile which is an adminstrator, but which is "inactive" (but not blocked) in Qlik Sense.  I have included this profile in the security rule for login access, just in case access should be necessary.

I am also logged into the QMC on another tab with my user profile which does have Qlik authority.

Any ideas?

René

**Comment by PlexPro** [comment]
Is anything in the EAPowerTools Service Dispatcher log significant (I haven't installed iPortal)?:

Date	Log Level	Service	Message
2017-01-24T15:39:58.832Z	INFO	EAPowerToolsService	Starting up the EAPowerTools Service Manager.
2017-01-24T15:39:58.870Z	INFO	EAPowerToolsService	Using default value of 'Info' for log level
2017-01-24T15:39:59.033Z	INFO	EAPowerToolsService	Could not parse service 'The file path 'C:\Program Files\Qlik\Sense\EAPowerTools\iportal\server.js' for service 'iPortal' is not valid (likely does not exist).' because: 'The file path 'C:\Program Files\Qlik\Sense\EAPowerTools\iportal\server.js' for service 'iPortal' is not valid (likely does not exist).'
2017-01-24T15:39:59.061Z	INFO	EAPowerToolsService	Found service 'QMCUtilities' in config file.
2017-01-24T15:39:59.062Z	INFO	EAPowerToolsService	Starting service: QMCUtilities

**Comment by ahmedmakki22** [comment]
Is this issue still exist? Plex, How did you manage to resolve it?
I experience exactly the same issue and couldn't find a way around it.

Your update will be much appreciated.

**Comment by goldbergjeffrey** [comment]
@ahmedmakki22 have you tried https?  Please make sure the EA Powertools Service Dispatcher is installed and running.

**Comment by PlexPro** [comment]
@ahmedmakki22 

The service QlikEAPowerToolsServiceDispatcher is running but we get no response when attempting to connect to "https://localhost:9945" (localhost worked for GMS), or using the full server name "https://vm-win-analytics.polywoodinc.local:9945".

**Comment by PlexPro** [comment]
@goldbergjeffrey 

Does the service (or other part of the program) do something which would require specific authority (log-in enough?  perhaps root admin?) to be defined in Qlik for the user which be logged into Windows and trying to work with the QMC Utilities in the browser?

In the stating of it, it makes sense, but I have not yet tested this.  I am getting things set up to log in with a user that does have defined Qlik authority.

Thanks,

René

**Comment by PlexPro** [comment]
Okay, I tried logging in to Windows with an account that has root admin authority granted in the QMC, and then attempted to go to https://localhost:9945/, with the same result.

So, I will wait until hearing something specific, or a new version, or perhaps Qlik Sense 3.1 installation later this month, to try again.

René

**Comment by goldbergjeffrey** [comment]
The QMC Utilities framework is not tied into Qlik Sense Server (yet).  It uses the QRS api to surface data, but that doesn't stop it from running at least the framework and the hello world page.  If you are receiving connection refused on port 9945 it could be a number it could be the following (none of which have anything to do with Qlik Sense, root admin, local admin accounts in windows or anything like that):

A. certificates: a certificate is required to run qmc utilities.  If you skipped this part and didn't point to a server certificate (like the Qlik Sense server certs located in programdata\qlik\sense\repository\exported certificates\.local certificates) then this may be your issue.

B. Firewall:  I know you have indicated firewall is off, but if you are accessing through something like aws you need to make sure 9945 is part of a security group.

C.  The aforementioned EA Powertools Service Dispatcher is not installed or not started.  Now I see from previous items in this thread that QMC Utils is "starting" but does it reach a "started" state?

At the end of the day I think some went wonky in your configuration during install.  In addition, you are running on Windows 10 if memory serves and we design our tools to work on server OS, not desktop OS so results may vary.

**Comment by ahmedmakki22** [comment]
@PlexPro @goldbergjeffrey 
I have deleted the EApowertools directory from c:\program files\qlik\sense\ and ran the installer exe again. everything woking fine now and managed to access the home page using the full server name: https://servername:9945

**Comment by PlexPro** [comment]
@goldbergjeffrey 

To reiterate, I have been installing and testing this on the server where Qlik Sense Enterprise server is installed.  This is a "true" server, running under Windows 2012 R2, System Type="Server, Stand-alone, Terminal Server, DataCenter".

> If you are receiving connection refused on port 9945 it could be a number it could be the following...:

> A. certificates: a certificate is required to run qmc utilities. If you skipped this part and didn't point to a server certificate ...then this may be your issue.

I had not specified an alternate host name, which would have required certificates, since I was running it on the server itself.  I am testing locally...

> B. Firewall: I know you have indicated firewall is off, but if you are accessing through something like aws you need to make sure 9945 is part of a security group.

I am testing locally -- from the server -- so the firewall should not be relevant, but I have tried it both entirely on or off, same result either way.

> C. The aforementioned EA Powertools Service Dispatcher is not installed or not started. Now I see from previous items in this thread that QMC Utils is "starting" but does it reach a "started" state?

The service itself is in "Running" state.

I uninstalled again, and supplied a simple host name ("servername").  It prompted for the certificates, and I specified "C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates\server.pem" and "C:\ProgramData\Qlik\Sense\Repository\Exported Certificates\.Local Certificates\server_key.pem".  Installation was successful.  The service was stopped and successfully restarted immediately.

No joy.

I uninstalled again, and reinstalled with the full compound host name ("servername.network.local").  No difference.

> At the end of the day I think some went wonky in your configuration during install.

Well, I have uninstalled and reinstalled three or four times since having resolved the service issue.  If there be some more thorough method of uninstallation, please let me know.

> In addition, you are running on Windows 10 if memory serves and we design our tools to work on server OS...

No.  QMC Utilities and the service are installed on the Qlik server, and that is where I am running the tests.

Thanks!  Once again, if there be a more thorough method of uninstallation, please let me know.

René

**Comment by PlexPro** [comment]
BTW, one of the events logged during installation; is it significant? :

Log Name:      Application
Source:        Qlik Sense Service Dispatcher
Date:          2/7/2017 9:50:42 AM
Event ID:      300
Task Category: None
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      VM-Win-Analytics.polywoodinc.local
Description:
The description for Event ID 300 from source Qlik Sense Service Dispatcher cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Qlik.batch-command (Batch command test) is disabled

**Comment by goldbergjeffrey** [comment]
I'm hoping this addresses your issue:

**[2.02 Installer](https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2)**

**Comment by PlexPro** [comment]
I installed 2.0.2.  The installation instructions in the setup program seemed clear to me, and since we are not using "a different hostname ... to access Qlik Sense externally", I did not specify an alternate hostname, since the Qlik Sense server is always accessed only by the internal network, either locally or by VPN.  However, the results were the same.

The version of Qlik Sense installed is still 2.2.4; we tentatively plan to effect the upgrade to 3.2 on Thursday.  If it does not start responding at that time, I will uninstall/reinstall again.

René

**Comment by gorkor** [comment]
We installed QMC Utilities 3.0.3
on two Sense servers (one is 3.2.SR1, the other 3.0.1.0)
and are having the same issues as PlexPro.

Locally pointing IE to https://localhost:9945/ gives 404 not found

**Comment by goldbergjeffrey** [comment]
@gorkor did you attempt https://localhost:9945/qmcu/.  This is the new url requirement for qmc utilities?  If not that, then if you look in the qmcutilities log folder are the qmc utilities starting?

jg

**Comment by gorkor** [comment]
Thanks! That works!
Seems the documentation needs an update, I don't see that url there.

/g

**Comment by goldbergjeffrey** [comment]
It's in the release notes... documentation does need some cleaning.
