### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rmbsrichard** [eapowertools/QlikSenseQMCUtility#51]
Hi 

I am getting a "Runtime Error (at 75:296) Cannot open file C:\Program Files\Qlik\Sense\\ServiceDispatcher\service.conf" error.  It appears that there is a  double forward slash "//" between "Sense" and "ServiceDispatcher.". Screen capture attached
![qmc util error](https://cloud.githubusercontent.com/assets/15189270/22483460/3d7bc76a-e862-11e6-9bcd-dde83dc808a9.PNG)

Cheers

Richard

**Comment by goldbergjeffrey** [comment]
interesting, did you change the install path?  The default installation path is programfiles\qlik\sense\eapowertools.  The eapowertools part of the path is missing from your screenshot.

**Comment by rmbsrichard** [comment]
Hi

No I did not change the default installation path

![image](https://cloud.githubusercontent.com/assets/15189270/22486124/1fb9e030-e86d-11e6-81d6-b25351f488c1.png)
 
![image](https://cloud.githubusercontent.com/assets/15189270/22486147/3b073374-e86d-11e6-8e3a-9607983390c4.png)

Cheers

Richard

**Comment by rmbsrichard** [comment]
OS = Windows 10, 
User is in the Administrators Group and used "run as administrator" to install

Cheers

Richard

**Comment by rmbsrichard** [comment]
Not sure if this helps, but if I look in Services, under Administrators Tools, I see the following
![image](https://cloud.githubusercontent.com/assets/15189270/22488272/e5177092-e875-11e6-891f-51a3be476570.png) The is a "//" between "EAPowerTools" and "PowerToolsServiceDispatcher"

**Comment by rmbsrichard** [comment]
Hi
The problem has now been sorted.  The problem was that Qlik Sense had been loaded on Drive E: were as QMC Utilities was been loaded on Drive C:  Once the install path was changed to E: Drive it worked.

Cheers

Richard
