### ISSUE TITLE
Not able to install QS QMC Utilities

### ISSUE THREAD

**Issue by greatsouls** [eapowertools/QlikSenseQMCUtility#53]
Trying to install the latest version of QS QMC Utilities (just downloaded it from https://community.qlik.com/docs/DOC-17521) and am getting below error (notice the double \\ in the middle of the path).
That path is constructed by the install wizard. It also assumes that Qlik Sense is installed in the default location. In my case I have it on D: and even if that double \\ is fixed it will still not find ServiceDispatcher folder in below path. Unfortunately the tools is not getting the correct install path and there is no way to point it to the correct folder (I have ServiceDispatcher at D:\Qliksense\ServiceDispatcher).
The tool searches ServiceDispatcher folder inside the newly created QMCUtilities folder which is not correct. ServiceDispathcer folder is on the same level, NOT inside QMCUtilities

![Uploading QS_QMC_Utilities.png…]()

**Comment by jparis** [comment]
The uploaded photo doesn't seem to work, could you try uploading it again?

**Comment by greatsouls** [comment]
It does not work for some reason. Getting "Something went really wrong, and we can’t process that file.  Choose Files. Try again"

I have sent an email with screenshots to Jeff Goldberg explaining the issue.

Regards,

**Comment by goldbergjeffrey** [comment]
The path issues should be addressed here.  An extra backslash was being added to paths.

**[2.02](https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2)**
