### ISSUE TITLE
Installation stopped while trying to install dispatcher.

### ISSUE THREAD

**Issue by mcafee44** [eapowertools/QlikSenseQMCUtility#56]
My default installation is not on the C: drive.  It is on E:  
At the point where I give my service account and password, a message comes up that the dispatcher has stopped.  Clicking OK I get 
'Cannot Open file E:\Program Files\Qlik\\Servicedispatcher\services.conf.'
(there are two slashes between qlik and servicedispatcher but the editor here removes one)
Looked for the file.  It is in 
'Cannot Open file E:\Program Files\Qlik\Sense\Servicedispatcher\services.conf.'

Not sure what to do here.

**Comment by goldbergjeffrey** [comment]
actually releasing a new installer this afternoon which will hopefully resolve the issue you are experiencing.

**Comment by goldbergjeffrey** [comment]
The path issues should be addressed here.  An extra backslash was being added to paths.

**[2.02 Installer](https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/2.0.2)**
