### ISSUE TITLE
Feature Request - Story / Bookmark approver

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/QlikSenseQMCUtility#57]
Currently Qlik Sense QMC Utilities > Sheet Approver approves sheets. Can this functionality be extended to other App.Objects like stories and bookmarks?

**Comment by goldbergjeffrey** [comment]
Sheet Approver has been replaced by app object approver.  Download the latest version of QMC Utilities ad you will have at least bookmark capabilities.  Stories should work too.

https://github.com/eapowertools/QlikSenseQMCUtility/releases/latest

**Comment by levi-turner** [comment]
Yep. Seem to work perfectly. Also https://github.com/eapowertools/QlikSenseQMCUtility/releases.atom slides into an RSS reader to stay up to date.

**Comment by goldbergjeffrey** [comment]
implemented in 3.0.3: **https://github.com/eapowertools/QlikSenseQMCUtility/releases/tag/3.0.3**

**Comment by levi-turner** [comment]
Yep! Thanks for the follow up.
