### ISSUE TITLE
Include Option for Desktop Shortcut to QMC Utils in Installation

### ISSUE THREAD

**Issue by rmterenzi** [eapowertools/QlikSenseQMCUtility#61]
URL configuration is in documentation but can be complex. Easier to supply a desktop shortcut, especially with the trailing forward slash requirement.

**Comment by goldbergjeffrey** [comment]
Won't fix.  Adding an icon with proper server name is a function of installer and with pending changes to installation methodology for QMC Utilities this is not possible.
