### ISSUE TITLE
AppMeta Fetcher does not grab user sheet information

### ISSUE THREAD

**Issue by FGrayQlik** [eapowertools/QlikSenseQMCUtility#65]
Testing the App Meta Fetcher to get statistics on user self service sheets and items that are created I have found that user sheets that are not published to get included.   I am using version 3.2 and the latest version of QMC Utilities.   Any help with this would be great.

**Comment by jparis** [comment]
At the moment, we aren't including this... I'll probably add this to the feature list, but pretty busy with other products right now. If you want to add it and merge it in, feel free.

**Comment by jparis** [comment]
Also, moving this issue to app-meta-fetcher repo and closing it here.
