### ISSUE TITLE
qmculogin.html location?

### ISSUE THREAD

**Issue by PlexPro** [eapowertools/QlikSenseQMCUtility#70]
Regarding these instructions at the end of the install process (I saw no reference to this in the install instructions):

"QMC Utilities uses the Qlik Sense proxy to properly authenticate users to the power tool.  In order to facilitate authentication and authorization in QMC Utilities, a stub page will be added to the **_default content library_** with the name qmculogin.html.  If the upload process fails, manually upload the the qmculogin.html file using the QMC.  The qmculogin.html file is located in the QMCUtilities root."

"WinHttp.WinHttpRequest:  A certificate is required to complete client authentication.  The authentication stub page qmculogin.html needs to be added to QMC content library manually."

Since the folder "C:\ProgramData\Qlik\Sense\Engine\Content\Default" was empty, I am inferring that this be where the "qmculogin.html" file is required?

[later edit] I see that "C:\ProgramData\Qlik\Sense\Repository\Content\Default" is also does not have this file...  It has some image files, but no html files.

[later edit] And then there is the "C:\ProgramData\Qlik\Sense\Repository\DefaultContent" folder, which is also empty but for another folder named "DefaultMediaLibrary".

Thanks,

René

**Comment by goldbergjeffrey** [comment]
@PlexPro, if the file does not get uploaded to the default content library you can upload it manually.  The file is located in %programfiles%\qlik\sense\eapowertools\qmcutilities.

You should see the file dropped there.  If not, then it's an installer bug.

**Comment by PlexPro** [comment]
@goldbergjeffrey, thank you, I did find the source location, what I'm not sure about is where it should be found to have been copied.

René
