### ISSUE TITLE
GMA export is already running, please wait for it to finish before triggering a new export.

### ISSUE THREAD

**Issue by PlexPro** [eapowertools/QlikSenseQMCUtility#72]
After a few times of successfully running the App Meta Fetcher, the last time it seemed to load only half the apps.

I tried several times to re-run it, thinking that certainly it had finished, given that it previously took less than a second.  Without a message to inform me of process termination/success, I couldn't infer a hung-up status from lack of such a message.

Well after logging out and in again a few times (due to the menu not appearing at the left underneath the menu tool button and the "Welcome rvalencourt" message), I finally got the menu again, and when I attempted to run the App Meta Fetcher, I got the message "GMA export is already running, please wait for it to finish before triggering a new export."

**How do I find this process to terminate it so that I can start over?  Is it safe to do so?**

I also have ten Console Window Host processes running under user "qliksensesvc".  Have these been left hanging by the App Meta Fetcher, or are they unrelated?

Thanks,

René V.

**Comment by PlexPro** [comment]
This finally finished, BUT...

I re-ran the App Meta Fetcher, and it again appeared to complete normally, with a count of 188 or something close to that, which is the number of apps that one can see in the QMC.

However, I have noted that the Governed Metrics App does not see all of these apps, even some commonly used ones.

I decided to reload the apps meta data, just to see if it might do a better job...  ha!... but again got the notice "GMA export is already running, please wait for it to finish before triggering a new export."

:(

René

**Comment by PlexPro** [comment]
The problem with the menu not appearing on the first or second attempt to display "https://localhost:9945/qmcu/home" also continues to reoccur.

**Comment by jparis** [comment]
Probably going to phase out the app-meta-fetcher and replace it with https://github.com/eapowertools/qs-governance-collector
