### ISSUE TITLE
problem to use

### ISSUE THREAD

**Issue by diogoguilhen** [eapowertools/QlikSenseQMCUtility#75]
I do the step by step into this link: https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities
but, i cant access because this error: 

`TypeError: Cannot read property 'sessionCookieHeaderName' of undefined    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\auth.js:38:50    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\rewrite.js:36:9    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\vpList.js:38:17    at tryCatcher (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\util.js:16:23)    at Promise._settlePromiseFromHandler (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:512:31)    at Promise._settlePromise (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:569:18)    at Promise._settlePromise0 (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:614:10)    at Promise._settlePromises (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:693:18)    at Async._drainQueue (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:133:16)    at Async._drainQueues (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:143:10)    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:17:14)    at processImmediate [as _immediateCallback] (timers.js:383:17)`

when i finish the installation  shows this error : 
'WinHttp.WinHttpRequest: The server name or address could not be resolved The authentication stub page qmculogin.html needs to be added to QMC content library manually.'

plz can help me?

**Comment by diogoguilhen** [comment]
i come to see EAPowerTools  log, and show this: 
Date	Log Level	Service	Message
2017-05-09T21:36:20.140Z	INFO	EAPowerToolsService	Starting up the EAPowerTools Service Manager.
2017-05-09T21:36:20.156Z	INFO	EAPowerToolsService	Using default value of 'Info' for log level
2017-05-09T21:36:20.156Z	INFO	EAPowerToolsService	Could not parse service 'The file path 'C:\Program Files\Qlik\Sense\EAPowerTools\iportal\server.js' for service 'iPortal' is not valid (likely does not exist).' because: 'The file path 'C:\Program Files\Qlik\Sense\EAPowerTools\iportal\server.js' for service 'iPortal' is not valid (likely does not exist).'
2017-05-09T21:36:20.156Z	INFO	EAPowerToolsService	Found service 'QMCUtilities' in config file.
2017-05-09T21:36:20.156Z	INFO	EAPowerToolsService	Starting service: QMCUtilities

**Comment by goldbergjeffrey** [comment]
@diogoguilhen 
you are experiencing two issues.
 
The first is that when you go to qmc utilities you need to make sure there is a trailing slash "/" after qmcu. If you don't have one you will get this error.
 
Second problem.  Because winhttp failed, the qmculogin.html stub page did not get loaded into the content library of the repository.  Go to QMC and upload the qmculogin.html page to the default content library.  The qmculogin.html file is located in the EAPowertools\QMCUtilities directory.

**Comment by diogoguilhen** [comment]
thx! i do it! only have a trouble with Certificate, mismatched Address, u know how solve this?

**Comment by goldbergjeffrey** [comment]
During QMCU install did you select friendly name for accessing?  If so, you need to supply a certificate.  That certificate needs to include a private key to secure communication.

**Comment by diogoguilhen** [comment]
how i can do the supply?

**Comment by goldbergjeffrey** [comment]
You would reinstall and make sure the checkbox asking to use existing configuration is unchecked.  Then you will be prompted if you want to use a friendly name to access qmc utilities.  If so, the next screen prompts adding a certificate.  However, that may not be your issue.

Did you install QMC Utilities on the Qlik Sense server or on another system?

**Comment by diogoguilhen** [comment]
i Install on qliksense Server... but i got other URL to config ... and i only can access with local machine.

**Comment by jparis** [comment]
Still any issue here? Reopen if there is with comments.
