### ISSUE TITLE
Repostory reload button needed?

### ISSUE THREAD

**Issue by PAdamsQlik** [eapowertools/QlikSenseQMCUtility#76]
Love the tool.  App Object Approver should be part of the core product.

Found an issue with App Object Approver... approval changes and other changes in the app (like publishing a sheet) are only refreshed from the repository upon the start of a new user session.  F5 and Shift-F5 did not help.  Only shutting down the browser and opening a new session helped.  Adding a repository reload button might be useful.

Using Sense 3.2.2.

**Comment by goldbergjeffrey** [comment]
@PAdamsQlik, there is an undocumented bug in 3.0.3 with appObjectApprover.  It will be fixed in 3.1.x hopefully released next week.

**Comment by goldbergjeffrey** [comment]
Fixed in https://github.com/eapowertools/qmcu-appobject-approver/commit/45978540ade54afa9a18eb12f35f91680da28aad

**Comment by goldbergjeffrey** [comment]
Related to #78
