### ISSUE TITLE
App Object Approver is not working

### ISSUE THREAD

**Issue by alexhausmann** [eapowertools/QlikSenseQMCUtility#78]
After selecting Community Sheets to be "published" to base sheet they hhange the status (Approved?)from "not approved" to "approved" by htting the "Approve Object" button. After refreshing QMC Utility and refreshing QMC the changes did where not applied.

Looks like changes are not stored / executed.

**Comment by goldbergjeffrey** [comment]
there is a small bug in the code.  Will be addressed in an upcoming patch targeted for next week.

**Comment by goldbergjeffrey** [comment]
fixed here: https://github.com/eapowertools/qmcu-appobject-approver/commit/45978540ade54afa9a18eb12f35f91680da28aad

Package happening today.

**Comment by goldbergjeffrey** [comment]
fixed in #82
