### ISSUE TITLE
Please make installation easier like other extensions

### ISSUE THREAD

**Issue by JayeshMule** [eapowertools/QlikSenseQMCUtility#79]
There are other extensions which we can import in QMC and use it. This process is easier so try to make this kind of extension installation for QMC Utility extension. Thanks

**Comment by goldbergjeffrey** [comment]
@JayeshMule, we are looking at ways to enhance the plugin deployment process.  We are considering moving away from a traditional installer and using an online repository approach for plugins.  The core QMC Utilities platform would have an installer, but the plugins would be downloaded from inside QMC Utilities or easily added via upload like extensions.  That said, QMC Utilities is not a visualization extension so it is not something you import into the QMC.

**Comment by jparis** [comment]
Work in progress. Closing this issue.
