### ISSUE TITLE
Installation documentation not available

### ISSUE THREAD

**Issue by ryrid** [eapowertools/QlikSenseQMCUtility#81]
When I click the link to go to the installation documentation it takes me directly to the homepage because it can't locate the document. 

https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities

**Comment by goldbergjeffrey** [comment]
Sorry about that, will have updated install documentation soon.  The installer is pretty straightforward so if you are feeling brave have a go.

**Comment by ryrid** [comment]
Thanks!

**Comment by goldbergjeffrey** [comment]
Updated Documentation here: https://github.com/eapowertools/QlikSenseQMCUtility/wiki/QMC-Utilities-Installation-Instructions
