### ISSUE TITLE
No menu after install

### ISSUE THREAD

**Issue by olcase** [eapowertools/QlikSenseQMCUtility#88]
After installing I do not get the menu, just a welcome message where I understand there should be a menu. 
![image](https://user-images.githubusercontent.com/29949195/27910821-0bcd49d6-6257-11e7-824d-daf76fb69cf5.png)

And thanks for making this sort of tool, it is beyond comprehension how the ability to approve a sheet is not build in to the the core product.

**Comment by goldbergjeffrey** [comment]
can you screenshot your dev tools console?

**Comment by olcase** [comment]
Hi, what is that?

**Comment by olcase** [comment]
Hey I guessed my way there. Adding /qmcu/appobjectapprover got me in to the right place.
