### ISSUE TITLE
Installation works fine but can't access QMCU pages

### ISSUE THREAD

**Issue by pcummins** [eapowertools/QlikSenseQMCUtility#89]
Hello,

I was able to successfully install QMC Utility however whenever I access the home page (ie https://qlikserver.com.au:9945/qmcu/) I just get what I see in the screenshot attached. 

https://user-images.githubusercontent.com/14995725/28402430-2c6b6ecc-6d63-11e7-9059-3b83c4a35d3c.png

Has anyone else experienced this across Qlik Sense 3.2 and Qlik Sense June 2017 editions?

Thanks,

Philip

**Comment by goldbergjeffrey** [comment]
Hi @pcummins, can you provide some screen shots of chrome dev tools?  Looks like you are getting some 404 issues rendering content.

**Comment by pcummins** [comment]
Hello,

OK testing again with https://localhost:9945/admin/qmcu/ (we have our primary site redirected to /admin for local logins) appears to work with SSL errors "Subject Alternative Name Missing" and certificate chain errors - it appears to be using the Qlik's built-in CA + hostname certificate - during the installation it didn't ask for any certificate information while installing as the Qlik Service account.

https://user-images.githubusercontent.com/14995725/28446189-8504a860-6e0c-11e7-88d6-173add3beb0e.png

Yesterday I was testing with the Qlik Sense server's FQDN which gives similar sign-in SSL errors:

https://user-images.githubusercontent.com/14995725/28446273-0a0b3c5e-6e0d-11e7-9d2a-51e3467d8512.png

Once signed in the resources can't be loaded due to net::ERR_INSECURE_RESPONSE:

https://user-images.githubusercontent.com/14995725/28446287-249ed6fc-6e0d-11e7-9379-cd48eba6ade6.png

I'm assuming localhost is preferable - is there a way to change just the certificate used for the QMCU pages?

Thanks,

Philip

**Comment by lucienorrin** [comment]
I get the same broken QMC Utilities page as op. 
When I encounter the issue I bounce the EAPowerTools service and it works for a short time.

**Comment by jparis** [comment]
The blocking of content I believe is a chrome setting.
