### ISSUE TITLE
Installation fails, QS 3.0.4

### ISSUE THREAD

**Issue by frankbilles** [eapowertools/QlikSenseQMCUtility#95]
Two findings.
1. the installation fails on Sense 3.0.4 with the error in the attached Screenshot
the installer searches for a file in a folder that doesnt exist
2. I cannot roll back the installtion from that point 
means I have many leftovers now in the system, with a non-complete installation
![qmcu-error](https://user-images.githubusercontent.com/32058535/30644355-67405b22-9e12-11e7-94eb-a0adf8003442.png)

**Comment by jparis** [comment]
If you try upgrading to 3.2 or higher, do you have the same issues? We won't be supporting the 3.0 track moving forward due to how old the release is and priorities of other issues. If you upgrade and still have problems, let us know and we'll see if we can get them sorted.
