### ISSUE TITLE
Source Control Lite not working on Sense September 2017

### ISSUE THREAD

**Issue by lucianoginqo** [eapowertools/QlikSenseQMCUtility#96]
Hello
I am testing QMC Utilities on QS September 2017 and noticed that the Source Control Lite function is not working. I cannot backup any app. Basically nothing happens when I click the Backup button. 
I found in the log file the following line(s)

{"module":"backupApp","level":"info","message":"Backing up 4c5178ba-891f-4676-b345-88cf77cd3a53","timestamp":"2017-10-10T17:07:27.174Z"}
{"module":"backupApp","level":"info","message":"Opening app 4c5178ba-891f-4676-b345-88cf77cd3a53","timestamp":"2017-10-10T17:07:27.189Z"}
{"module":"backupApp","level":"error","message":"{\"code\":1009,\"parameter\":\"4c5178ba-891f-4676-b345-88cf77cd3a53\",\"message\":\"App already open in different mode\"}","timestamp":"2017-10-10T17:07:27.189Z"}

Any ideas?
Thank you

**Comment by ChristofSchwarz** [comment]
I am running QS Sept 2017 (Patch 1) and the Backup of a Sense App was working, it prouced a .zip file with multiple .json files inside. However, the Restore starts "spinning wheel" after picking the same .zip, but never finishes the restore.

**Comment by jparis** [comment]
@lucianoginqo Seems like the app is already open, I'd close all your sessions and try again, if that doesn't work, try restarting the Engine Service then trying again. If that ALL still doesn't work, post the error message up here.

Thanks!
